services:
  agent:
    build: ./agent
    ports:
      - "8080:8080"
    env_file: .env

  fraud-risk-analysis-agent:
    build: ./fraud-risk-analysis-agent
    ports:
      - "8081:8080"
    env_file: .env

  ui:
    build: ./ui
    ports:
      - "8501:8080"
    environment:
      - AGENT_ENDPOINT_URL=http://agent:8080
    depends_on:
      - agent